config/routes.rb
Rails.application.routes.draw do
   devise_for :users
   root to: 'prototypes#index'

   resources :prototypes do
    resources :comments, only: [:create]
   end

   resources :users, only: [:show]
   resources :prototypes, only: [:index, :new, :create, :destroy, :edit, :update, :show] 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :prototype  
  belongs_to :user  
  validates :text, presence: true
end

app/models/prototype.rb
class Prototype < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  has_one_attached :image

  validates :name, presence: true
  validates :catch_copy, presence: true
  validates :concept, presence: true
  validates :image, presence: true
  validates :text, presence: true, unless: :was_attached?


  def was_attached?
    self.image.attached?
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 
  validates :name, presence: true
  validates :profile, presence: true
  validates :occupation, presence: true
  validates :position, presence: true

  has_many :comments, dependent: :destroy
  has_many :prototypes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :profile, :occupation, :position])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController 
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to prototype_path(@comment.prototype) # 今回の実装には関係ありませんが、このようにPrefixでパスを指定することが望ましいです。
    else
      @prototype = @comment.prototype
      @comments = @prototype.comments
      render "prototypes/show" # views/tweets/show.html.erbのファイルを参照しています。
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, prototype_id: params[:prototype_id])
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_prototype, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @prototypes = Prototype.all
  end

  def show
    @prototype = Prototype.find(params[:id])
    @comment = Comment.new
    @comments = @prototype.comments.includes(:user)
  end

  def new
    @prototype = Prototype.new
  end

  def create
    @prototype = current_user.prototypes.build(prototype_params)
    if @prototype.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @prototype = Prototype.find(params[:id])
  end

  def update
    @prototype = Prototype.find(params[:id])
    if @prototype.update(prototype_params)
      redirect_to prototype_path(@prototype)
    else
    render :edit
   end
  end

  def destroy
    @prototype.destroy
    redirect_to root_path
  end

  private

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end

  def set_user
    @user = @prototype.user
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end

  def prototype_params
    params.require(:prototype).permit(:name, :catch_copy, :concept, :image).merge(user_id: current_user.id)
  end

  def authorize_user!
    unless @prototype.user == current_user
      redirect_to root_path
    end
  end

  def correct_user
      @prototype = Prototype.find(params[:id])
    unless @prototype.user == current_user
        redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @name = @user.name
    @prototypes = @user.prototypes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Protospace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } %>
              <%= link_to "New Proto", new_prototype_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/prototypes/_form.html.erb
  <%= form_with model: prototype, local: true do |f|%> 
  <% if prototype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prototype.errors.count, "error") %> prohibited this prototype from being saved:</h2>
      <ul>
        <% prototype.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :name, "プロトタイプの名称" %><br />
    <%= f.text_field :name, id:"prototype_title" %>
  </div>

  <div class="field">
    <%= f.label :catch_copy, "キャッチコピー" %><br />
    <%= f.text_area :catch_copy, class: :form__text, id:"prototype_catch_copy" %>
  </div>

  <div class="field">
    <%= f.label :concept, "コンセプト" %><br />
    <%= f.text_area :concept, class: :form__text, id:"prototype_concept" %>
  </div>

  <div class="field">
    <%= f.label :image, "プロトタイプの画像" %><br />
    <%= f.file_field :image, id:"prototype_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/prototypes/_prototype.html.erb
<div class="card">
  <% if prototype.image.attached? %>
   <%= link_to prototype_path(prototype) do %>
    <%= image_tag prototype.image.variant(resize: '500x500'), class: 'prototype-image' %>
   <% end %>
  <% end %>

  <div class="card-content">
    <h3 class="card-title">
      <%= link_to prototype.name, prototype_path(prototype) %></h3>
    <p class="card-catch-copy"><%= prototype.catch_copy %></p>
    <p class="card-concept"><%= prototype.concept %></p>
    <%# <p class="card-user"><%= link_to "#{prototype.user.name}", prototype_path(prototype), class: 'prototype-link'</p>  %>
    <p class="card-user"><%= link_to "#{prototype.user.name}", user_path(prototype.user), class: 'prototype-link' %></p> 
    <%# <%= link_to "by #{@prototype.user.name}", user_path(@prototype.user), class: "prototype__user" %> 
  </div>
</div>

app/views/prototypes/edit.html.erb
<div class="main">
  <div class="inner">
   <div class="form__wrapper">
    <h2 class="page-heading">プロトタイプ編集</h2>
      <%= render 'form', prototype: @prototype %>
    </div>
  </div>
</div>

app/views/prototypes/index.html.erb
<main class="main">
  <div class="inner"> 
    <% if user_signed_in? %> 
      <div class="greeting">
        こんにちは、   
         <%= link_to "#{current_user.name}さん", user_path(current_user), class: :greeting__link %> 
      </div>
    <% end %>

    <div class="card__wrapper">
      <% @prototypes.each do |prototype| %> 
        <%= render partial: 'prototype', locals: { prototype: prototype } %> 
      <% end %>
    </div>
  </div>
</main>

app/views/prototypes/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規プロトタイプ投稿</h2>
        <%= render 'form', prototype: @prototype %>
    </div>
  </div>
</div>

app/views/prototypes/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @prototype.name %>
      </p>
      <%= link_to "by #{@prototype.user.name}", user_path(@prototype.user), class: "prototype__user" %>
      <% if user_signed_in? && @prototype.user == current_user %>
        <div class="prototype__manage">
          <%= link_to "編集", edit_prototype_path(@prototype), class: "prototype__btn" %>
          <%= link_to "削除", prototype_path(@prototype), method: :delete, data: { turbo_method: :delete }, class: "prototype__btn" %>
        </div>
      <% end %>

      <div class="prototype__image">
        <% if @prototype.image.attached? %>
          <%= image_tag @prototype.image.variant(resize: '500x500'), class: 'prototype-image' %>
        <% else %>
          <p>画像がありません</p>
        <% end %>
      </div>

      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @prototype.catch_copy %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= @prototype.concept %>
          </p>
        </div>
      </div>

  <div class="container">
    <h4>コメント</h4>
    <% if user_signed_in? %>
      <%= form_with(model: [@prototype, @comment], local: true) do |form| %>
        <%= form.text_area :text, rows: "1" %> 
        
        <div class="actions">
        <%= form.submit "送信する" %>
        </div>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>

    <div class="comments">
      <% @prototype.comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.name, user_path(comment.user) %>:</strong>
          <%= comment.text %> 
        </p>
       <% end %>

        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%# <%= "ユーザー名さんの情報"%> 
        <%= "#{@user.name}さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <%# <td class="table__col2"><%= "ユーザー名" %></td> 
            <td class="table__col2"><%= "#{@user.name}" %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= "#{@user.profile}" %></td>
          </tr>
          <tr>
            <th class="table__col1">所属</th>
            <td class="table__col2"><%= "#{@user.occupation}" %></td>
          </tr>
          <tr>
            <th class="table__col1">役職</th>
            <td class="table__col2"><%= "#{@user.position}" %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.name}さんのプロトタイプ"%>
      </h2>
      <div class="user__card">
        <%= render partial: "prototypes/prototype", collection: @user.prototypes %>
      </div>
    </div>
  </div>
</div>